version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.2-node
      - image: circleci/postgres:11.2
    steps:
      - checkout
      - ruby/install-deps
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.7.2-node
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: todo_list_graphql_rails
          POSTGRES_DB: todo_list_graphql_rails_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: todo_list_graphql_rails
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test
      - ruby/rubocop-check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
